services:
  - name: host
    type: web
    env: python
    build:
      pip install -r requirements.txt
    start: python host_lipu.py
    envVars:
      - key: TOKEN
        value: your-telegram-bot-token
      - key: OWNER_ID
        value: your-telegram-user-id
      - key: ADMIN_ID
        
    plan: free
    healthCheckPath: /
